### ISSUE TITLE
File fragmented message is cleared too quickly

### ISSUE THREAD

**Issue by steve6375** [a1ive/grub2-filemanager#138] opened 2020-03-20 19:15 UTC
If an .iso file is selected, a message showing that the file is fragmented is displayed too quickly for the user to read.
Add a 
`sleep 3`
line?
![image](https://user-images.githubusercontent.com/1469350/77198471-f0980500-6ade-11ea-90e8-ce362802ebf8.png)

**Comment by steve6375** [comment] 2020-03-20 20:40
I added sleep 3 and also read to loop_detect.sh and it seems to be ignored?
in fact echo lines are also ignored in /boot/grubfm/rules/iso/loop_detect.sh !! Something very odd going on!

**Comment by a1ive** [comment] 2020-03-22 11:17
???
https://github.com/a1ive/grub2-filemanager/blob/1866b1ac1f3798b06d575b464147829f8679c893/boot/grubfm/rules/iso/e2b.sh#L3-L10

**Comment by steve6375** [comment] 2020-03-22 11:29
I am just selecting a .iso file in agFM - so it should run  loop_detect.sh, but the message appears BEFORE loop_detect.sh is run.
The message seems to be coming from somewhere else.
It is not the same message
The message is 'File is NOT contiguous''  - is seems to come from grubfm_open call ???

**Comment by a1ive** [comment] 2020-03-22 11:35
I can't reproduce it.

**Comment by steve6375** [comment] 2020-03-22 11:45
Do you have a fragmented ISO file?
![image](https://user-images.githubusercontent.com/1469350/77248608-ab84e780-6c32-11ea-9200-0a4e432ff919.png)

**Comment by a1ive** [comment] 2020-03-22 11:51
![深度截图_选择区域_20200322194834](https://user-images.githubusercontent.com/10670106/77248715-8ade8100-6c76-11ea-9dd7-f58630aede9b.png)
![深度截图_选择区域_20200322194928](https://user-images.githubusercontent.com/10670106/77248716-8ca84480-6c76-11ea-94bc-58a3786887a9.png)

**Comment by a1ive** [comment] 2020-03-22 11:52
"unknown argument ---is-x86-bios-bootsector" error fixed in https://github.com/a1ive/grub2-filemanager/commit/455978026d85f759c58782f62f86a5c33f6d43c8

**Comment by a1ive** [comment] 2020-03-22 11:52
"unknown argument ---is-x86-bios-bootsector" error fixed in https://github.com/a1ive/grub2-filemanager/commit/455978026d85f759c58782f62f86a5c33f6d43c8

**Comment by steve6375** [comment] 2020-03-22 11:53
OK - but where does the message come from and is there a delay?

**Comment by a1ive** [comment] 2020-03-22 12:32
> where does the message come from

check e2b.sh or e2b_test.sh?

**Comment by steve6375** [comment] 2020-03-22 12:45
ah - its stat -c  in e2b_test.sh

I can add a sleep 3 in...

source ${prefix}/func.sh;

probe --set=fs -f "${grubfm_device}";
if [ "${fs}" != "fat" -a "${fs}" != "exfat" -a "${fs}" != "ntfs" ];
then
  set grubfm_test=0;
  return;
fi;
stat --set=frag -c "${grubfm_file}";
if [ "${frag}" != "1" ];
then
  set grubfm_test=0;
  **sleep 3**
  return;
fi;

**Closed** 2020-03-22 17:32 UTC
